### PR TITLE
Feat/fix multi started tasks M2-530

### PR DESCRIPTION
**Pull request by hparfr**

### CODE REVIEW

**Comment by waf31** [comment]
Hi i have put this on staging for Dawid. For me looks ok, nice and clean. I will merge this after i have green light from Dawid. To this time even when the fix will be accepted we can not merge it with master.

**Comment by hparfr** [comment]
Ok but, when accepted, in which branch you want it to be merged ?

**Comment by waf31** [comment]
This is good question, for this moment we can not merge it with master. Dawid is waiting for other ticket to finish (M2-506), if this ticket will be finished then he will allow us to push the start button to production.

**Comment by waf31** [comment]
This can be merged with release ERP-2020-28

**Pull request merged**
